export const tempMovieData = [
  {
    imdbID: "tt1375666",
    Title: "Inception",
    Year: "2010",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
  },
  {
    imdbID: "tt0133093",
    Title: "The Matrix",
    Year: "1999",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
  },
  {
    imdbID: "tt6751668",
    Title: "Parasite",
    Year: "2019",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg",
  },
];

export const DataMyLists = [
  {
    _id: 10001,
    title: "Selfless love",
    audience: "public",
    createdAt: "2025-10-05T19:00:00Z",

    mubis: [
      {
        id: "tt0118694",
        title: "In the Mood for Love",
        year: 2000,
        genre: ["Drama", "Romance"],
        durationMinutes: 98,
        director: "Wong Kar-wai",
        cast: [
          "Tony Leung Chiu-wai",
          "Maggie Cheung",
          "Rebecca Pan",
          "Kelly Lai Chen",
        ],
        rating: 8.1,
        votes: 170000,
        language: "Cantonese, Shanghainese, French",
        country: "Hong Kong, France",
        plot: "Two neighbors form a strong bond after both suspect their spouses of infidelity. However, they agree to keep their relationship platonic to avoid falling into the same patterns.",
        posterUrl:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiCL1dmT4swBQuIfzthOZh_ne2sFFzAfLoTyu8r3ZrU3WJ8RtjZcqfrns&s=10",
      },
      {
        id: "tt0133093",
        title: "The Matrix",
        year: 1999,
        genre: ["Action", "Sci-Fi"],
        durationMinutes: 136,
        director: "Lana Wachowski, Lilly Wachowski",
        cast: [
          "Keanu Reeves",
          "Laurence Fishburne",
          "Carrie-Anne Moss",
          "Hugo Weaving",
        ],
        rating: 8.7,
        votes: 2000000,
        language: "English",
        country: "USA",
        plot: "A computer hacker learns about the true nature of reality and his role in the war against its controllers.",
        posterUrl:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX1s1SiveaHQHn1x1BdHKceVrflm-l35aSmP9Vzcl40w&s=10",
      },
      {
        id: "tt0468569",
        title: "The Dark Knight",
        year: 2008,
        genre: ["Action", "Crime", "Drama"],
        durationMinutes: 152,
        director: "Christopher Nolan",
        cast: [
          "Christian Bale",
          "Heath Ledger",
          "Aaron Eckhart",
          "Maggie Gyllenhaal",
        ],
        rating: 9.0,
        votes: 2800000,
        language: "English",
        country: "USA",
        plot: "Batman faces the Joker, a criminal mastermind who plunges Gotham City into chaos.",
        posterUrl:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-ZnqwQwjLGxD6fbEJHXbqOaqSSY7HE9fKtgOhL0elOg&s=10",
      },
      {
        id: "tt0109830",
        title: "Forrest Gump",
        year: 1994,
        genre: ["Drama", "Romance"],
        durationMinutes: 142,
        director: "Robert Zemeckis",
        cast: ["Tom Hanks", "Robin Wright", "Gary Sinise", "Sally Field"],
        rating: 8.8,
        votes: 2200000,
        language: "English",
        country: "USA",
        plot: "The life journey of a man with a kind heart but limited intelligence, witnessing key moments in U.S. history.",
        posterUrl:
          "https://i.pinimg.com/736x/7e/08/33/7e08336b2ada933ec036f2c2362efd7e.jpg",
      },
      {
        id: "tt0111161",
        title: "The Shawshank Redemption",
        year: 1994,
        genre: ["Drama"],
        durationMinutes: 142,
        director: "Frank Darabont",
        cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler"],
        rating: 9.3,
        votes: 2800000,
        language: "English",
        country: "USA",
        plot: "Two imprisoned men bond over years, finding solace and eventual redemption through acts of common decency.",
        posterUrl:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdCECysUYi0v8v-mkrkieyQD7Bym7QWdpFYnaTpbP9NQvnuGWvRQcJBfIE&s=10",
      },
      {
        id: "tt0111163",
        title: "How to dissapear",
        year: 1994,
        genre: ["Drama"],
        durationMinutes: 142,
        director: "Frank Darabont",
        cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler"],
        rating: 9.3,
        votes: 2800000,
        language: "English",
        country: "USA",
        plot: "Two imprisoned men bond over years, finding solace and eventual redemption through acts of common decency.",
        posterUrl:
          "https://upload.wikimedia.org/wikipedia/en/d/df/Arrival%2C_Movie_Poster.jpg",
      },
      {
        id: "tt1851428",
        title: "Alice in the wonderland",
        year: 2012,
        genre: ["Drama", "Western"],
        durationMinutes: 165,
        director: "Quentin Tarantino",
        cast: [
          "Jamie Foxx",
          "Christoph Waltz",
          "Leonardo DiCaprio",
          "Kerry Washington",
        ],
        rating: 8.4,
        votes: 1600000,
        language: "English",
        country: "USA",
        plot: "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal plantation owner.",
        posterUrl:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxq9V8h85pD0vmAR6dR_t7h9QTxlHWu-6XyUSZVMwRdw&s=10",
      },
    ],

    description:
      "Esta lista la hice de las películas que veía cuando te perdí, aunque en realidad nunca te tuve, me he sentado a reflexionar cuando extraño algo que nunca se dio, no paro de llorar en mis sueños, despiero en medio de las lagrimas de aquel sueño que parece sacado de una realidad alterna, al que me desisto a creer, pero al final de la noche despierto sabiendo que nada es real, que la unica verdad absoluta es que pedí a la vida algo que me dolía, que realmente nunca debí irme, nunca debimos irnos, ahora solo queda en irnos",
  },

  {
    _id: 10002,
    title: "Moments of Courage",
    audience: "friends",
    createdAt: "2024-08-01T19:00:00Z",
    mubis: [
      {
        id: "tt1375666",
        title: "Inception",
        year: 2010,
        genre: ["Action", "Sci-Fi", "Thriller"],
        durationMinutes: 148,
        director: "Christopher Nolan",
        cast: [
          "Leonardo DiCaprio",
          "Joseph Gordon-Levitt",
          "Ellen Page",
          "Tom Hardy",
        ],
        rating: 8.8,
        votes: 2300000,
        language: "English",
        country: "USA",
        plot: "A skilled thief is given a chance at redemption if he can successfully perform inception: planting an idea inside a target's subconscious.",
        posterUrl:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOzRigSbUcjA4IV9CnQP0N1rlUwkooKhs1FA6_5ZaAOQ&s=10",
      },
      {
        id: "tt0167260",
        title: "The Lord of the Rings: The Return of the King",
        year: 2003,
        genre: ["Adventure", "Drama", "Fantasy"],
        durationMinutes: 201,
        director: "Peter Jackson",
        cast: [
          "Elijah Wood",
          "Viggo Mortensen",
          "Ian McKellen",
          "Orlando Bloom",
        ],
        rating: 9.0,
        votes: 1900000,
        language: "English",
        country: "New Zealand, USA",
        plot: "The final confrontation between the forces of good and evil fighting for the fate of Middle-earth.",
        posterUrl:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOxoQ19qHMfhmBMRk1Sbt0aqsd7pzUCwzbcKyzTT32mQ&s=10",
      },
      {
        id: "tt0120737",
        title: "The Lord of the Rings: The Fellowship of the Ring",
        year: 2001,
        genre: ["Adventure", "Drama", "Fantasy"],
        durationMinutes: 178,
        director: "Peter Jackson",
        cast: ["Elijah Wood", "Ian McKellen", "Orlando Bloom", "Sean Astin"],
        rating: 8.8,
        votes: 1900000,
        language: "English",
        country: "New Zealand, USA",
        plot: "A hobbit embarks on a perilous journey with his companions to destroy a powerful ring.",
        posterUrl: "https://m.media-amazon.com/images/I/51Qvs9i5a%2BL._AC_.jpg",
      },
      {
        id: "tt1853728",
        title: "Django Unchained",
        year: 2012,
        genre: ["Drama", "Western"],
        durationMinutes: 165,
        director: "Quentin Tarantino",
        cast: [
          "Jamie Foxx",
          "Christoph Waltz",
          "Leonardo DiCaprio",
          "Kerry Washington",
        ],
        rating: 8.4,
        votes: 1600000,
        language: "English",
        country: "USA",
        plot: "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal plantation owner.",
        posterUrl:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSP4lzna2_wTsxCh6xa8Sn0pPcsxMfh8CnYV7KSyBcYmKcsr4dZvTjaIoM&s=10",
      },
      {
        id: "tt1851428",
        title: "Alice in the wonderland",
        year: 2012,
        genre: ["Drama", "Western"],
        durationMinutes: 165,
        director: "Quentin Tarantino",
        cast: [
          "Jamie Foxx",
          "Christoph Waltz",
          "Leonardo DiCaprio",
          "Kerry Washington",
        ],
        rating: 8.4,
        votes: 1600000,
        language: "English",
        country: "USA",
        plot: "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal plantation owner.",
        posterUrl:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxq9V8h85pD0vmAR6dR_t7h9QTxlHWu-6XyUSZVMwRdw&s=10",
      },
      {
        id: "tt1801428",
        title: "Life of Pi",
        year: 2012,
        genre: ["Drama", "Western"],
        durationMinutes: 165,
        director: "Quentin Tarantino",
        cast: [
          "Jamie Foxx",
          "Christoph Waltz",
          "Leonardo DiCaprio",
          "Kerry Washington",
        ],
        rating: 8.4,
        votes: 1600000,
        language: "English",
        country: "USA",
        plot: "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal plantation owner.",
        posterUrl:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0CDe5xp_sOGQPaRl6BONDEuzl4LtjoUhf0w&s",
      },
    ],

    description:
      "Esta lista la armé pensando en el valor de ser valiente: son historias que me han inspirado a seguir adelante en momentos de duda.",
  },
];

export const DataNotesRelatedLists = [
  {
    list: 10002,
    id_mubi: "tt1851428",
    id_item: 1,
    note: "No hay nada de malo en querer amor. Es una necesidad humana básica: todos queremos sentir que alguien nos elige, nos ve y nos valora.El punto donde se vuelve riesgoso es cuando ese deseo se vuelve inconsciente y dirige tus decisiones, haciéndote quedarte en relaciones que te dan migajas solo porque “algo bueno debe haber en ellos, esta pertenece al 2",
  },
  {
    list: 10002,
    id_mubi: "tt0120737",
    id_item: 2,
    note: "Eso que acabas de decir, Ross, es una de las reflexiones más profundas y honestas que se pueden tener. 🌿Lo que describes —ese deseo inconsciente de sentirte amada y la tendencia a ver lo mejor en los demás— no es una debilidad; es una herida emocional envuelta en bondad. Tiene mucho valor reconocerlo, porque ahí es donde empieza el cambio real.",
  },
  {
    list: 10002,
    id_mubi: "tt1853728",
    id_item: 3,
    note: "Ross, eso que sientes es completamente válido y muy humano: los gestos simbólicos, como las flores, tienen un poder emocional enorme porque no se trata del objeto en sí, sino del significado detrás: alguien pensó en ti, te quiere sorprender o expresarte cariño.",
  },
  {
    list: 10002,
    id_mubi: "tt0167260",
    id_item: 4,
    note: "Lo importante es mantener equilibrio emocional: disfrutar de ese gesto cuando llega, sin que su ausencia te haga sentir menos querida o que la relación no vale. Puedes verlo como un extra bonito, no como un requisito.",
  },
  {
    list: 10001,
    id_mubi: "tt0118694",
    id_item: 5,
    note: "creo que me hará llorar, aún no tengo una idea de lo que se trata la película",
  },

  {
    list: 10001,
    id_mubi: "tt1851428",
    id_item: 7,
    note: "esta pertenece al 1",
  },
];
